name: todo_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  
  json_serializable: ^6.1.3

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^19.4.41

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7

  mobx_codegen: ^2.0.5+2

  json_annotation: ^4.4.0

flutter:
  uses-material-design: true
